// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDMnDA_lUVXl8oqmmjTZAyNzNYSGKNmc8s",
    authDomain: "hack-a10bb.firebaseapp.com",
    projectId: "hack-a10bb",
    storageBucket: "hack-a10bb.appspot.com", // ✅ FIXED
    messagingSenderId: "937705200109",
    appId: "1:937705200109:web:8265f895c9ec2f7a46efe4",
    measurementId: "G-HWLRE3ZHDV",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWf5G-Xav5lT3FoDzoyXQwonIKNB8R9k',
    appId: '1:937705200109:android:9b7989d794b0564246efe4',
    messagingSenderId: '937705200109',
    projectId: 'hack-a10bb',
    databaseURL: 'https://hack-a10bb-default-rtdb.firebaseio.com',
    storageBucket: 'hack-a10bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAcSsG9NTF9PJ0eODCnKd-GUk-IxkvDWI',
    appId: '1:937705200109:ios:55486f7995dd998c46efe4',
    messagingSenderId: '937705200109',
    projectId: 'hack-a10bb',
    databaseURL: 'https://hack-a10bb-default-rtdb.firebaseio.com',
    storageBucket: 'hack-a10bb.appspot.com',
    iosClientId:
        '937705200109-9ne82lcfipltmb3u94nvegpgltpsmrum.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisanSaathiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAcSsG9NTF9PJ0eODCnKd-GUk-IxkvDWI',
    appId: '1:937705200109:ios:55486f7995dd998c46efe4',
    messagingSenderId: '937705200109',
    projectId: 'hack-a10bb',
    databaseURL: 'https://hack-a10bb-default-rtdb.firebaseio.com',
    storageBucket: 'hack-a10bb.appspot.com',
    iosClientId:
        '937705200109-9ne82lcfipltmb3u94nvegpgltpsmrum.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisanSaathiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMnDA_lUVXl8oqmmjTZAyNzNYSGKNmc8s',
    appId: '1:937705200109:web:24e10d2642b0022c46efe4',
    messagingSenderId: '937705200109',
    projectId: 'hack-a10bb',
    authDomain: 'hack-a10bb.firebaseapp.com',
    databaseURL: 'https://hack-a10bb-default-rtdb.firebaseio.com',
    storageBucket: 'hack-a10bb.appspot.com',
    measurementId: 'G-LVL74VB3DS',
  );
}
